jobscript: "../slurm-jobscript.sh"
cluster: "../slurm-submit.py"
cluster-status: "../slurm-status.py"
cluster-sidecar: "../slurm-sidecar.py"
cluster-cancel: "scancel"
max-jobs-per-second: 1
max-status-checks-per-second: 10
snakefile: "../../workflow/Snakefile"
cores: 256
jobs: 256
latency-wait: 60
printshellcmds: true
rerun-incomplete: true
use-singularity: true
singularity-args: "--bind $PWD/../../../zarp,$TMPDIR"
default-resources: mem_mb=1024
restart-times: 3
keep-going: true
notemp: false
no-hooks: true
verbose: true
