jobscript: "../slurm-jobscript.sh"
cluster: "../slurm-submit.py"
cluster-status: "../slurm-status.py"
snakefile: "../../workflow/Snakefile"
cores: 256
jobs: 256
printshellcmds: true
rerun-incomplete: true
use-singularity: true
singularity-args: "--bind $PWD/../../../zarp"
keep-going: true
notemp: false
no-hooks: true
verbose: true
