jobscript: "../slurm-jobscript.sh"
cluster: "../slurm-submit.py"
cluster-status: "../slurm-status.py"
snakefile: "../../workflow/Snakefile"
cores: 256
jobs: 256
printshellcmds: true
rerun-incomplete: true
use-conda: true
conda-frontend: conda
keep-going: true
notemp: false
no-hooks: true
verbose: true
